﻿﻿// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Task2Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Task2Infrastructure.Migrations
{
    [DbContext(typeof(BooksContext))]
    [Migration("20201030081415_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Products")
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Task2.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Genre")
                        .IsRequired();

                    b.Property<double>("Price")
                        .IsRequired();
                    
                    b.Property<bool>("Novelty")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Book","Products");
                });
#pragma warning restore 612, 618
        }
    }
}
